### ISSUE TITLE
Removing an archer element from DOM causes crash

### ISSUE THREAD

**Issue by cole-robertson** [pierpo/react-archer#96]
I am working on a tree view structure. When I remove one of the nodes from my tree (wrapped in an archer element) I get the error: `Uncaught TypeError: Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'.` from React Archer.

I'm not sure if you have seen this issue before, but removing the archer container and archer elements from my project works as expected.

**Comment by pierpo** [comment]
Hello!

Are you seeing this on the latest version? I published a fix recently, but I might have missed something.

Thanks :blush:

**Comment by cole-robertson** [comment]
Thank you! Yes the update seemed to fix that problem, however I can only see the fix by removing the <svg>s absolute positioning from the dom. I am now unable to click on any of my ArcherElement forms in my ArcherContainer without removing that svg positioning. Is there something I need to do to get them back on "top"?

**Comment by cole-robertson** [comment]
I used to also have my grid styling (column row) on the ArcherElement itself. It seems that this updated also broke that. It may be related to the unclickable elements that I am having too. To fix the positioning issue, I can wrap the ArcherElements in a div with my grid styles, but I still cannot click.

**Comment by pierpo** [comment]
Interesting!
I did break something with 2.0.0: I used to add an additional div inside `ArcherElement`, which I stopped doing. It might break your layout indeed! If you want to keep the same layout as before, you may add the additional div yourself:

`<ArcherElement><div>Hello</div></ArcherElement>` -> `<ArcherElement><div><div>Hello</div></div></ArcherElement>` 

About the unclickable element... I am not sure, I will have a look.
This change might have had an impact but it's weird.

**Comment by pierpo** [comment]
I updated the release note to make it more explicit. Thank you.

**Comment by cole-robertson** [comment]
Ah that makes sense! I was not able to reproduce in the issue in a CodeSandbox, but I was able to fix it in my project by adding a div with position relative directly under the ArcherContainer.
`<ArcherContainer>
   <div style={{position: relative}}>
   ...
   </div>
 </ArcherContainer>
`

Also could you link me to the release notes?

**Comment by pierpo** [comment]
Sure, here it is: https://github.com/pierpo/react-archer/releases/tag/v2.0.0

Thank you for pointing out this issue, I had not realized this release would break existing layouts. I thought it would only break for usages with multiple children to ArcherElement.

**Comment by pierpo** [comment]
The unclickable element was very likely linked to this https://github.com/pierpo/react-archer/issues/97

Thank you for reporting an issue!
